theme: minima
title: Brian's World
author: Brian Scott
email: brian.scott@briansworld.com
description: > # this means to ignore newlines until "baseurl:"
  All things Brian.

# social links
twitter_username: nunyabusiness
github_username:  brianscott1968

show_excerpts: true # set to false to remove excerpts on the homepage
